// data.js — mock recipes + pantry items for Pantry Pal

// Photos from Unsplash (free hotlink)
const photo = (id, w = 1200) => `https://images.unsplash.com/photo-${id}?w=${w}&q=80&auto=format&fit=crop`;

window.PANTRY_PAL_DATA = {
  user: {
    name: 'Sam',
    streak: 12,
    cookedThisWeek: 4,
    cuisinesThisWeek: ['Italian', 'Thai', 'Mexican'],
  },

  // Pantry: ingredient name, qty label, category, freshness 0-1 (1 = fresh, 0 = bad), location
  pantry: [
    { id: 'carrots', name: 'Carrots', qty: '~1 lb', said: 'a bunch of carrots', cat: 'Produce', loc: 'fridge', fresh: 0.35, added: '5 days ago', expiring: true },
    { id: 'spinach', name: 'Baby spinach', qty: '~5 oz', said: 'almost-full bag of spinach', cat: 'Produce', loc: 'fridge', fresh: 0.25, added: '6 days ago', expiring: true },
    { id: 'onion-yellow', name: 'Yellow onions', qty: '~2', said: 'an onion or two', cat: 'Produce', loc: 'pantry', fresh: 0.85, added: '1 wk ago' },
    { id: 'garlic', name: 'Garlic', qty: '1 head', cat: 'Produce', loc: 'pantry', fresh: 0.9, added: '1 wk ago' },
    { id: 'lemon', name: 'Lemons', qty: '2', cat: 'Produce', loc: 'fridge', fresh: 0.6, added: '4 days ago' },
    { id: 'cilantro', name: 'Cilantro', qty: '~1 bunch', said: 'cilantro looking a little sad', cat: 'Produce', loc: 'fridge', fresh: 0.4, added: '4 days ago', expiring: true },
    { id: 'tomato', name: 'Roma tomatoes', qty: '4', cat: 'Produce', loc: 'pantry', fresh: 0.7, added: '3 days ago' },
    { id: 'ginger', name: 'Ginger root', qty: '~2 in', said: 'a little knob of ginger', cat: 'Produce', loc: 'fridge', fresh: 0.65 },

    { id: 'chicken-thigh', name: 'Chicken thighs', qty: '~1 lb', said: 'thighs from yesterday', cat: 'Protein', loc: 'fridge', fresh: 0.55, added: '2 days ago' },
    { id: 'eggs', name: 'Eggs', qty: '8', cat: 'Protein', loc: 'fridge', fresh: 0.8 },
    { id: 'chickpeas', name: 'Chickpeas (can)', qty: '2 cans', cat: 'Protein', loc: 'pantry', fresh: 1 },

    { id: 'rice-jasmine', name: 'Jasmine rice', qty: '~2 lb', cat: 'Grains', loc: 'pantry', fresh: 1 },
    { id: 'pasta-penne', name: 'Penne', qty: '~¾ box', said: 'most of a box of penne', cat: 'Grains', loc: 'pantry', fresh: 1 },
    { id: 'tortilla', name: 'Corn tortillas', qty: '12', cat: 'Grains', loc: 'pantry', fresh: 0.7 },

    { id: 'olive-oil', name: 'Olive oil', qty: '~half', cat: 'Pantry', loc: 'pantry', fresh: 1 },
    { id: 'soy', name: 'Soy sauce', qty: '~full', cat: 'Pantry', loc: 'pantry', fresh: 1 },
    { id: 'cumin', name: 'Cumin', qty: '1 jar', cat: 'Spices', loc: 'pantry', fresh: 1 },
    { id: 'paprika', name: 'Smoked paprika', qty: '1 jar', cat: 'Spices', loc: 'pantry', fresh: 1 },
    { id: 'chili-flakes', name: 'Chili flakes', qty: '~half', cat: 'Spices', loc: 'pantry', fresh: 1 },
    { id: 'salt', name: 'Kosher salt', qty: '1 box', cat: 'Spices', loc: 'pantry', fresh: 1 },
    { id: 'pepper', name: 'Black pepper', qty: '1 grinder', cat: 'Spices', loc: 'pantry', fresh: 1 },

    { id: 'yogurt', name: 'Greek yogurt', qty: '~½ tub', said: 'half a tub of yogurt', cat: 'Dairy', loc: 'fridge', fresh: 0.5, added: '5 days ago' },
    { id: 'parmesan', name: 'Parmesan', qty: '1 wedge', cat: 'Dairy', loc: 'fridge', fresh: 0.85 },
    { id: 'butter', name: 'Butter', qty: '1 stick', cat: 'Dairy', loc: 'fridge', fresh: 0.9 },
  ],

  // Recipes — match calc done at runtime from `need` vs pantry ids
  recipes: [
    {
      id: 'carrot-ginger-soup',
      title: 'Charred carrot & ginger soup',
      blurb: 'Whole roasted carrots, ginger, lemon. Bright and silky.',
      time: 35, difficulty: 'Easy', cuisine: 'Modern',
      photo: photo('1547592180-85f173990554'),
      need: ['carrots', 'ginger', 'onion-yellow', 'garlic', 'olive-oil', 'lemon', 'salt'],
      missing: [],
      expiringUsed: ['carrots'],
      tags: ['vegetarian', 'soup'],
      ingredients: [
        { id: 'carrots', amt: '1 lb', have: true },
        { id: 'ginger', amt: '2-in piece', have: true },
        { id: 'onion-yellow', amt: '1 large', have: true },
        { id: 'garlic', amt: '3 cloves', have: true },
        { id: 'olive-oil', amt: '3 tbsp', have: true },
        { id: 'lemon', amt: '½', have: true },
        { id: 'stock', name: 'Vegetable stock', amt: '4 cups', have: false },
      ],
      steps: [
        { t: 'Heat oven to 425°F.', dur: null },
        { t: 'Toss carrots and onion in olive oil, salt. Roast on a sheet pan until deeply charred at the edges, 25 min.', dur: 25 * 60 },
        { t: 'Meanwhile, grate ginger; smash garlic.', dur: null },
        { t: 'In a pot, warm 1 tbsp oil. Add ginger + garlic, 30 sec. Add roasted veg + stock. Simmer 10 min.', dur: 10 * 60 },
        { t: 'Blend until silky. Finish with lemon juice and a glug of olive oil. Salt to taste.', dur: null },
      ],
    },
    {
      id: 'shakshuka',
      title: 'Spinach shakshuka',
      blurb: 'Soft eggs in a smoky tomato sauce with wilted spinach.',
      time: 25, difficulty: 'Easy', cuisine: 'Middle Eastern',
      photo: photo('1590412200988-a436970781fa'),
      need: ['eggs', 'tomato', 'spinach', 'onion-yellow', 'garlic', 'paprika', 'cumin', 'olive-oil'],
      missing: [],
      expiringUsed: ['spinach'],
      tags: ['vegetarian', 'quick'],
      ingredients: [
        { id: 'eggs', amt: '4', have: true },
        { id: 'tomato', amt: '4 (or 1 can)', have: true },
        { id: 'spinach', amt: '3 oz', have: true },
        { id: 'onion-yellow', amt: '½', have: true },
        { id: 'garlic', amt: '2 cloves', have: true },
        { id: 'paprika', amt: '1 tsp', have: true },
        { id: 'cumin', amt: '½ tsp', have: true },
      ],
      steps: [
        { t: 'Sweat diced onion in olive oil, 5 min.', dur: 5 * 60 },
        { t: 'Add garlic, paprika, cumin. Bloom 30 sec.', dur: 30 },
        { t: 'Crush in tomatoes. Simmer until jammy, 8 min.', dur: 8 * 60 },
        { t: 'Stir in spinach. Make 4 wells; crack eggs in.', dur: null },
        { t: 'Cover and cook until whites set, yolks runny, 4 min.', dur: 4 * 60 },
      ],
    },
    {
      id: 'chicken-rice',
      title: 'Cilantro-lime chicken rice bowl',
      blurb: 'Crispy thighs, fluffy jasmine rice, herby yogurt.',
      time: 30, difficulty: 'Easy', cuisine: 'Mexican',
      photo: photo('1546069901-ba9599a7e63c'),
      need: ['chicken-thigh', 'rice-jasmine', 'cilantro', 'lemon', 'yogurt', 'garlic', 'cumin', 'olive-oil', 'salt'],
      missing: [],
      expiringUsed: ['cilantro'],
      tags: ['protein', 'bowl'],
      ingredients: [
        { id: 'chicken-thigh', amt: '4 thighs', have: true },
        { id: 'rice-jasmine', amt: '1 cup', have: true },
        { id: 'cilantro', amt: '½ bunch', have: true },
        { id: 'lemon', amt: '1', have: true },
        { id: 'yogurt', amt: '½ cup', have: true },
        { id: 'garlic', amt: '2 cloves', have: true },
        { id: 'cumin', amt: '1 tsp', have: true },
      ],
      steps: [
        { t: 'Rinse rice; cook in 1.5 cups water with salt, 15 min covered.', dur: 15 * 60 },
        { t: 'Pat thighs dry. Rub with cumin, salt, pepper.', dur: null },
        { t: 'Sear skin-side down in hot pan, 7 min. Flip; cook 5 min more.', dur: 12 * 60 },
        { t: 'Whisk yogurt with minced garlic, lemon zest, chopped cilantro.', dur: null },
        { t: 'Fluff rice with lemon juice. Plate; top with chicken and herby yogurt.', dur: null },
      ],
    },
    {
      id: 'penne-arrabbiata',
      title: 'Penne arrabbiata',
      blurb: '20-min weeknight pasta. Spicy, garlicky, simple.',
      time: 20, difficulty: 'Easy', cuisine: 'Italian',
      photo: photo('1551183053-bf91a1d81141'),
      need: ['pasta-penne', 'tomato', 'garlic', 'chili-flakes', 'olive-oil', 'parmesan', 'salt'],
      missing: [],
      tags: ['vegetarian', 'quick', 'pantry'],
      ingredients: [
        { id: 'pasta-penne', amt: '8 oz', have: true },
        { id: 'tomato', amt: '4', have: true },
        { id: 'garlic', amt: '4 cloves', have: true },
        { id: 'chili-flakes', amt: '1 tsp', have: true },
        { id: 'parmesan', amt: 'to finish', have: true },
      ],
      steps: [
        { t: 'Boil salted water. Cook penne until just under al dente.', dur: 9 * 60 },
        { t: 'Sliver garlic; gently fry in olive oil with chili flakes.', dur: 3 * 60 },
        { t: 'Crush tomatoes in; simmer 6 min.', dur: 6 * 60 },
        { t: 'Toss pasta in sauce with a splash of pasta water. Plate with parm.', dur: null },
      ],
    },
    {
      id: 'thai-basil-chicken',
      title: 'Thai basil chicken (krapao)',
      blurb: 'Punchy stir-fry over rice with a crispy fried egg.',
      time: 20, difficulty: 'Medium', cuisine: 'Thai',
      photo: photo('1512058564366-18510be2db19'),
      need: ['chicken-thigh', 'rice-jasmine', 'garlic', 'soy', 'chili-flakes', 'eggs'],
      missing: ['basil', 'fish-sauce', 'oyster-sauce'],
      tags: ['protein', 'spicy'],
      ingredients: [
        { id: 'chicken-thigh', amt: '1 lb, chopped', have: true },
        { id: 'rice-jasmine', amt: '1.5 cups', have: true },
        { id: 'garlic', amt: '5 cloves', have: true },
        { id: 'soy', amt: '2 tbsp', have: true },
        { id: 'chili-flakes', amt: '1 tsp', have: true },
        { id: 'eggs', amt: '2', have: true },
        { id: 'basil', name: 'Thai basil', amt: '1 cup', have: false },
        { id: 'fish-sauce', name: 'Fish sauce', amt: '1 tbsp', have: false },
        { id: 'oyster-sauce', name: 'Oyster sauce', amt: '1 tbsp', have: false },
      ],
      steps: [
        { t: 'Steam jasmine rice.', dur: 15 * 60 },
        { t: 'Pound garlic + chili in a mortar.', dur: null },
        { t: 'Stir-fry chicken in screaming hot oil with garlic-chili paste, 3 min.', dur: 3 * 60 },
        { t: 'Splash in soy, fish sauce, oyster sauce. Toss with Thai basil.', dur: null },
        { t: 'Fry an egg in lots of oil until edges are crisp. Serve over rice.', dur: 3 * 60 },
      ],
    },
    {
      id: 'crispy-chickpea-bowl',
      title: 'Crispy chickpea & yogurt bowl',
      blurb: 'Pantry-raid lunch. Smoky chickpeas, lemony yogurt, herbs.',
      time: 18, difficulty: 'Easy', cuisine: 'Mediterranean',
      photo: photo('1512621776951-a57141f2eefd'),
      need: ['chickpeas', 'yogurt', 'lemon', 'paprika', 'cumin', 'olive-oil', 'cilantro', 'garlic'],
      missing: [],
      tags: ['vegetarian', 'quick', 'pantry'],
      ingredients: [
        { id: 'chickpeas', amt: '1 can', have: true },
        { id: 'yogurt', amt: '½ cup', have: true },
        { id: 'lemon', amt: '½', have: true },
        { id: 'paprika', amt: '1 tsp', have: true },
        { id: 'cumin', amt: '½ tsp', have: true },
        { id: 'cilantro', amt: 'few sprigs', have: true },
      ],
      steps: [
        { t: 'Drain & dry chickpeas. Toss with olive oil, paprika, cumin.', dur: null },
        { t: 'Fry in a hot pan until crisp, 8 min, tossing.', dur: 8 * 60 },
        { t: 'Whisk yogurt with grated garlic, lemon juice, salt.', dur: null },
        { t: 'Schmear yogurt; pile chickpeas on. Shower with cilantro.', dur: null },
      ],
    },
    {
      id: 'carrot-fritters',
      title: 'Carrot–herb fritters',
      blurb: 'Crispy patties with yogurt-lemon sauce. Uses up half a bag.',
      time: 25, difficulty: 'Easy', cuisine: 'Modern',
      photo: photo('1565299624946-b28f40a0ae38'),
      need: ['carrots', 'eggs', 'cilantro', 'yogurt', 'lemon', 'cumin', 'garlic'],
      missing: ['flour'],
      expiringUsed: ['carrots', 'cilantro'],
      tags: ['vegetarian'],
      ingredients: [
        { id: 'carrots', amt: '3, grated', have: true },
        { id: 'eggs', amt: '2', have: true },
        { id: 'cilantro', amt: '½ bunch', have: true },
        { id: 'yogurt', amt: '½ cup', have: true },
        { id: 'flour', name: 'All-purpose flour', amt: '¼ cup', have: false },
      ],
      steps: [
        { t: 'Grate carrots; squeeze out water in a towel.', dur: null },
        { t: 'Mix with eggs, flour, cumin, salt, chopped cilantro.', dur: null },
        { t: 'Pan-fry in olive oil until deeply golden, 3 min per side.', dur: 6 * 60 },
        { t: 'Serve with garlicky yogurt.', dur: null },
      ],
    },
    {
      id: 'tortilla-soup',
      title: 'Quick tortilla soup',
      blurb: 'Spicy broth, crispy tortilla strips, lime. 25 min.',
      time: 25, difficulty: 'Easy', cuisine: 'Mexican',
      photo: photo('1455619452474-d2be8b1e70cd'),
      need: ['tortilla', 'tomato', 'onion-yellow', 'garlic', 'cumin', 'lemon', 'cilantro'],
      missing: ['chicken-stock', 'avocado'],
      tags: ['quick', 'soup'],
      ingredients: [
        { id: 'tortilla', amt: '4', have: true },
        { id: 'tomato', amt: '3', have: true },
        { id: 'onion-yellow', amt: '½', have: true },
        { id: 'cilantro', amt: 'handful', have: true },
      ],
      steps: [
        { t: 'Slice tortillas; fry in oil until crisp. Salt.', dur: 5 * 60 },
        { t: 'Sweat onion & garlic. Add cumin, then tomato. Simmer 8 min.', dur: 8 * 60 },
        { t: 'Add stock; simmer 5 min.', dur: 5 * 60 },
        { t: 'Top with tortilla strips, lime, cilantro.', dur: null },
      ],
    },
  ],

  cuisines: ['All', 'Italian', 'Mexican', 'Thai', 'Middle Eastern', 'Mediterranean', 'Modern', 'Japanese', 'Indian'],

  // For the onboarding chat sample
  onboardingTurns: [
    { role: 'bot', text: "Hi! I'm Pal. Tell me what's in your kitchen — fridge, freezer, pantry, the half-bag of carrots you forgot about. Voice or type, whatever's easiest." },
  ],
};
